name: test
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: YYun-D/i18n_test
          
      - name: Sync files with dst-repsotiory!
        uses: waroad/sync-files@main
        with:
          git-author-email: 'yeoyundong@gmail.com'
          git-author-name: 'YYun-D'
          sync-repository: Azure/azure-sdk
          allow-files-pattern: '^docs/policies/README-EXAMPLE.md|^docs/policies/support.md'
          sync-branch-name: 'main'
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install python module
        run: |
          pip install --upgrade pip
          pip install mdpo
          
      - name: mdfile change to pofile
        run: |
          md2po ./docs/policies/README-EXAMPLE.md -q -s -p ./docs/policies/ko/README-EXAMPLEko.po
          md2po ./docs/policies/support.md -q -s -p ./docs/policies/ko/supportko.po
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          add-paths: |
            docs/policies/README-EXAMPLE.md
            docs/policies/support.md
            docs/policies/ko/README-EXAMPLEko.po
            docs/policies/ko/supportko.po
          branch: sync/YYun-D/i18n_test

