name: remote pull request
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          token: ${{ secrets.PAS_TOKEN }}
          path: YYun-D/i18n_test
          commit-message: Update po file
          committer: YYun-D <yeo1998@naver.com>
          branch: main
