name: Pull Request

on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: move files
      run : |
        mkdir -p docs/po/policies
        mv docs/policies/README-EXAMPLE.md docs/po/policies/README-EXAMPLE.md
        mv docs/policies/support.md docs/po/policies/support.md

    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAS_TOKEN }}
      with:
        source_folder: './docs'
        destination_repo: 'YYun-D/blog'
        destination_head_branch: 'test'
        user_email: 'yeo1998@naver.com'
        user_name: 'YYun-D'
