name: test
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: YYun-D/i18n_test
      - name: Sync files with dst-repsotiory!
        uses: waroad/sync-files@main
        with:
          git-author-email: 'yeoyundong@gmail.com'
          git-author-name: 'YYun-D'
          sync-repository: Azure/azure-sdk
          allow-files-pattern: '^docs/policies/README-EXAMPLE.md|^docs/policies/support.md'
          sync-branch-name: 'main'
      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'docs/policies/README-EXAMPLE.md'
          destination_repo: 'YYun-D/i18n_test'
          destination_folder: 'docs'
          destination_base_branch: 'main'
          destination_head_branch: 'main'
          user_email: 'yeoyundong@gmail.com'
          user_name: 'YYun-D'
          pull_request_reviewers: 'reviewers'

