name: pull-request
on:
  push:
    branches: [ sync/YYun-D/i18n_test ]
    
  workflow_dispatch:
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.0
