name: push_from_weblate
on:
  push:
      branches:
        - main
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  build:
    name: push_from_weblate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: devrel-kr/I18N-For-Beginners
          
      - name: record log
        run : |
          git log --index.html > commits.txt
          cat commits.txt
      
